user_input =  input("Would You like to adopt a cat? ('Y' for yes 'N' for no )")

if user_input == "Y" : 
 # we used == because it is used for comparision and = is used to assign a value. == is comparision operator and = is assignment operator
    print("You are such a nice human!")
elif user_input == "N" :
    print(" You deranged psycopath" )
else :
    print("You cant even read?? You have to answer in Y or N.... Even cat has higher iq than you. Bozo!")
