print("welcome to the madlibs practice 1")
print("Today I went to a ________ (Place)")
place = input("Enter a name of a place")
print("There i saw a ________ (Subject)")
subject = input("Enter The subject of the story ")
print(f"The {subject} was very ______(adjective) and was ______ (verb in ing form)")
adjective1 = input("Enter a adjective :")
verb = input("Enter The verb")
print(f"By seeing the {subject} I was _______ (adjective)")
adjective2 = input("Enter a adjective")
print("The story is completed")
print (" Here is your full story")
print(f"Today I went to a {place}")
print(f"There i saw a {subject}")
print(f"The {subject} was very {adjective1} and was {verb})")
print(f"By seeing the {subject} I was {adjective2}")
print("Thanks!!!")

