place = input("Enter a name of a place:")
subject = input("Enter the subject of the story:")
adjective1 = input("Enter a adjective:")
verb = input("Enter a verb:")
adjective2 = input("Enter another adjective:")
print(f"Today i went to a {place}")
print(f"There i saw a {subject}")
print(f"The {subject} was {adjective1} and {verb}")
print(f"By looking at the {subject} i felt {adjective2}")
